### ISSUE TITLE
Hi! I need help

### ISSUE THREAD

**Issue by amitchai** [marvpaul/Ultimate-Tetris-3D-Unity#2]
Hello, 
First of all, I want to make sure that it's ok to use your code, to create Tetris on Gear VR.
2nd, I am running your project on Unity Editor, and everything is great. but on mobile (GearVR), Everything is working except that the Line is not deleting when is Full. I am not sure what's wrong... 
I made some tests, and I do believe it's somewhere here:

for(int i = 0; i < isFullLine.Count; i++){
			//Delete all cubes in a row
			foreach (GameObject cube in GameObject.FindGameObjectsWithTag("Cube")) {
				int y = (int)cube.transform.position.y;
				if(isFullLine[i] == y){
					//Heres goes a incredible cool explosion effect!!!
					Destroy (cube); 
				}
			}
			//Set down all cubes above the deleted row
			foreach (GameObject cube in GameObject.FindGameObjectsWithTag("Cube")) {
				int y = (int)cube.transform.position.y;
				if(isFullLine[i] < y){
					cube.transform.position += Vector3.down; 
				}
			}
			gameObject.GetComponent<ManageAudio> ().PlayFullLine (); 

			for (int j = 0; j < isFullLine.Count; j++) {
				isFullLine [j] -= 1;
			}
		}

Hope you can help solve this! Thanks!
Amit

**Comment by marvpaul** [comment]
Hey. Yes, feel free to use for non commercial projects. Feel free to create a pull request in case you‘ve done some improvements.
So the bug only happens when you start a compiled version of the game? In Editor all works as expected?
That sound like a really crazy bug. 
Can you give some more information about occurrences of the bug? Which build setting, platform ...

**Comment by amitchai** [comment]
Cool. Thanks a lot for quick response. Im using unity latest ver. 2018.1.6 i think. Android platform. I can send u the project

**Comment by amitchai** [comment]
Also, this is for commercial project 🤔 but i dont mind sharing revenu if will be any..

**Comment by marvpaul** [comment]
Hey. Any news? Do you have finished the project?
