### ISSUE TITLE
Issue with understanding the code

### ISSUE THREAD

**Issue by lelouch0204** [marvpaul/Ultimate-Tetris-3D-Unity#3]
Hello I wanted to know what the following line meant
`isCube = new bool[10,17];`
I am having trouble in understanding as to what 10 and 17 represent here? The horizontal and vertical lengths of the grid?

**Comment by marvpaul** [comment]
It’s a two dimensional array which represents the grid of the tetris game. 10 is the length in x direction / horizontal and 17 is the length in y direction / vertical I think. 
In this array each Boolean entry signals if there is a cube on that certain position or not I guess.
For example the value of isCube[1][10] Stores the information if a cube is currently at coordinates x=1 and y=10 or not. Hope it helps
