### ISSUE TITLE
Add license request 

### ISSUE THREAD

**Issue by Tisks** [marvpaul/Ultimate-Tetris-3D-Unity#4]
I'm interested in forking and modifying your game code in order to advance in my undergraduate thesis. 

The game will be used as an example to test some mechanics and it wont be used commercially in the forseeable future (the actual software I'm working on is in it's early development stage and possibly will be open source)

I cannot use this repo without a license since according to https://help.github.com/articles/licensing-a-repository/ it is effectively cannot be used without your written permission.

An open source license would suit my needs a the moment.

I provide you with a summary of the open licences here : https://gist.github.com/nicolasdao/a7adda51f2f185e8d2700e1573d8a633#file-open_source_licenses-md

I hope I can use your code fairly because helps my cause grandly

**Comment by marvpaul** [comment]
Here we go! Hope it is what you're looking for. I don't want to allow commercial use right now, so I've chosen the same license Shadertoy.com offers (Attribution-NonCommercial-ShareAlike 3.0 Unported). I guess that's enough, so you can use it in your thesis, right?

**Comment by Tisks** [comment]
> Here we go! Hope it is what you're looking for. I don't want to allow commercial use right now, so I've chosen the same license Shadertoy.com offers (Attribution-NonCommercial-ShareAlike 3.0 Unported). I guess that's enough, so you can use it in your thesis, right?

Thanks! it fits the requirements for my thesis based on what I had read about the BY-NC-SA
